name: hyf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - biopython=1.85=py313h536fd9c_1
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - c-blosc2=2.15.2=h68e2383_0
  - ca-certificates=2025.9.9=h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - deepdiff=8.4.2=pyhd8ed1ab_0
  - dipy=1.10.0=py313ha87cce1_1
  - et_xmlfile=1.1.0=py313h06a4308_1
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - h5py=3.12.1=py313h5842655_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=hd590300_1001
  - matplotlib=3.10.0=py313h06a4308_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=pyh267e887_2
  - nibabel=5.3.2=pyha770c72_1
  - numexpr=2.10.1=py313h3c60e43_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py313h5eee18b_1
  - openssl=3.5.0=h7b32b05_1
  - orderly-set=5.3.0=pyh29332c3_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313ha87cce1_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py313hcea889d_0
  - pip=25.0=py313h06a4308_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycirclize=1.9.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.7.1=py313h6a678d5_0
  - pyqt6-sip=13.9.1=py313h5eee18b_0
  - pytables=3.10.2=py313h759fa19_1
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=0_cp313
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.8.0=py313ha014f3b_0
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scikit-image=0.25.2=py313ha87cce1_0
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.1=py313hf4aebb8_0
  - setuptools=72.1.0=py313h06a4308_0
  - setuptools-scm=8.2.1=pyhd8ed1ab_0
  - sip=6.10.0=py313h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.4=py313ha014f3b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.2.18=py313h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py313h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trx-python=0.3=py313h78bf25f_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.2.4=h7955e40_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - attrs==25.4.0
      - captum==0.8.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - filelock==3.13.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - idna==3.10
      - jinja2==3.1.4
      - kneed==0.8.5
      - lxml==5.4.0
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - nilearn==0.11.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - propcache==0.4.1
      - psutil==7.1.0
      - requests==2.32.3
      - sympy==1.14.0
      - torch==2.7.0+cu126
      - torch-cluster==1.6.3+pt27cu126
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu126
      - torch-sparse==0.6.18+pt27cu126
      - torch-spline-conv==1.2.2+pt27cu126
      - torchaudio==2.7.0+cu126
      - torchvision==0.22.0+cu126
      - triton==3.3.0
      - urllib3==2.4.0
      - yarl==1.22.0
prefix: /home/hyf/.conda/envs/hyf
